package com.yubico.webauthn.data

import com.fasterxml.jackson.core.JsonGenerator
import com.fasterxml.jackson.databind.JsonSerializer
import com.fasterxml.jackson.databind.SerializerProvider
import com.fasterxml.jackson.databind.annotation.JsonSerialize


private class ACPSerializer extends JsonSerializer[AttestationConveyancePreference] {
  override def serialize(t: AttestationConveyancePreference, jsonGenerator: JsonGenerator, serializerProvider: SerializerProvider): Unit =
    jsonGenerator.writeString(
      t match {
        case NonePreference => "none"
        case Indirect => "indirect"
        case Direct => "direct"
      }
    )
}

object AttestationConveyancePreference {
  val default: AttestationConveyancePreference = NonePreference
}

/**
  * Relying Parties may use this to specify their preference regarding
  * attestation conveyance during credential generation.
  */
@JsonSerialize(using = classOf[ACPSerializer])
sealed trait AttestationConveyancePreference

/**
  * Indicates that the Relying Party is not interested in authenticator
  * attestation.
  *
  * For example, in order to potentially avoid having to obtain
  * user consent to relay identifying information to the Relying Party, or to
  * save a roundtrip to an Attestation CA.
  *
  * This is the default value.
  */
case object NonePreference extends AttestationConveyancePreference

/**
  * Indicates that the Relying Party prefers an attestation conveyance yielding
  * verifiable attestation statements, but allows the client to decide how to
  * obtain such attestation statements. The client MAY replace the
  * authenticator-generated attestation statements with attestation statements
  * generated by an Anonymization CA, in order to protect the user’s privacy,
  * or to assist Relying Parties with attestation verification in a
  * heterogeneous ecosystem.
  *
  * Note: There is no guarantee that the Relying Party will obtain a verifiable
  * attestation statement in this case. For example, in the case that the
  * authenticator employs self attestation.
  */
case object Indirect extends AttestationConveyancePreference

/**
  * Indicates that the Relying Party wants to receive the attestation statement
  * as generated by the authenticator.
  */
case object Direct extends AttestationConveyancePreference
