# This name is shown in the status badge in the README
name: code-formatting

on:
  push:
    branches-ignore:
      - 'tmp**'
  pull_request:
    branches-ignore:
      - 'tmp**'

jobs:
  test:
    name: JDK ${{matrix.java}}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [25]
        distribution: [temurin]

    steps:
    - name: Check out code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7 => v7.0.1

    - name: Set up JDK
      uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6  # v6 => v6.0.1
      with:
        java-version: ${{ matrix.java }}
        distribution: ${{ matrix.distribution }}

    - name: Check code formatting
      run: ./gradlew spotlessCheck
